inherit_from: [configs/dataset/config_base_3RScan_full_l160.yaml,configs/method/config_base_3DSSG.yaml]
model:
  multi_rel: true # multiple relationship 
wandb:
  tags: ["ssg", "3dssg","full","l20"]

data:
  input_type: pcd
  classes_relations_dir: "./files"

eval:
  data_workers: 1